pipeline {
    agent {
        node {
            label 'centos'
        }
    }

    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            agent {
                docker {
                    reuseNode true
                    image 'autodesk-docker.art-bobcat.autodesk.com:10873/digital-help/node-12-react:latest'
                    args '-p 3001:3001'
                }
            }
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            agent {
                docker {
                    reuseNode true
                    image 'autodesk-docker.art-bobcat.autodesk.com:10873/digital-help/node-12-react:latest'
                    args '-p 3001:3001'
                }
            }
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            agent {
                docker {
                    reuseNode true
                    image 'autodesk-docker.art-bobcat.autodesk.com:10873/digital-help/node-12-react:latest'
                    args '-p 3001:3001'
                }
            }
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
